[package]
name = "run"
version = "0.1.0"
edition = "2021"
description = "⚡ A tool to manage end execute your scripts."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
